language: python
python:
 - "3.3"
 - "3.4"
 - "3.5"
env:
  matrix:
   - DJANGO="Django<1.8"
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
install:
 - pip install "$DJANGO" coverage coveralls djangorestframework
 - pip install .
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django<1.8"
    - python: "3.3"
      env: DJANGO="Django<1.10"
branches:
 only:
  - master
script:
  - coverage run manage.py test
after_success:
  - coverage report
  - coveralls
